name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run code cavarage (tarpaulon)
      uses: actions-rs/tarpaulin@v0.1
      with: 
        version: '0.15.0'
        args: '-- --test-threads 1'
    - name: Run linter (clippy)
      run: cargo clippy -- -D warnings
    - name: Run formatting (fmt)
      run: cargo fmt -- --check
    - name: Run audit check
      uses: actions-rs/audit-check@v1.2.0
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
